"""
Policy Explainability module for explaining RL agent actions.
"""

from typing import Any, Optional
from llm_rl.llm.base import BaseLLM
from llm_rl.prompts import EXPLAIN_ACTION_PROMPT_TEMPLATE, SYSTEM_PROMPT


class PolicyExplainer:
    """
    Generates natural language explanations for agent decisions under given state observations.
    """

    def __init__(self, llm: BaseLLM, env_name: str = "CartPole-v1"):
        self.llm = llm
        self.env_name = env_name

    def explain_action(
        self,
        observation: Any,
        action: Any,
        action_meaning: Optional[str] = None,
        env_info: Optional[str] = None
    ) -> str:
        """
        Generate natural language explanation for state-action pair.

        Args:
            observation: State vector or representation.
            action: Selected action.
            action_meaning: Human-readable action description (e.g., 'Push Cart Right').
            env_info: Additional domain context.

        Returns:
            Explanation text generated by LLM.
        """
        obs_str = str(observation)
        act_str = str(action)
        meaning_str = action_meaning or f"Action Code {action}"
        info_str = env_info or "Standard Gymnasium environment dynamics."

        prompt = EXPLAIN_ACTION_PROMPT_TEMPLATE.format(
            env_name=self.env_name,
            observation=obs_str,
            action=act_str,
            action_meaning=meaning_str,
            env_info=info_str
        )

        return self.llm.generate(prompt, system_prompt=SYSTEM_PROMPT)
